### ISSUE TITLE
UI Checklist

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [StationWare/stationware#133]
- [ ] Show how many points a player has in the corner of their screen
- [ ] Show whether a player won or lost
- [ ] Flash the challenge number (first, second, third, challenge etc etc) at the center of the screen
- [ ] Flash the challenge text at the top of the screen rather than in the text (cause mfers can spam text with how fast they scream)

**Comment by Just-a-Unity-Dev** [comment]
Honestly we dont need that 3rd thing
